[profile.default]
src = 'src'
test = 'src/test'
out = 'out/foundry'
cache_path = 'out/foundry-cache'
broadcast = 'out/foundry-broadcast'
fs_permissions = [
  { access = "read-write", path = "./"}
]
allow_paths= ['../../node_modules']
remappings= [
  '@openzeppelin/=../../node_modules/@openzeppelin/',
  'forge-std/=../../node_modules/forge-std/src/',
  'ds-test/=../../node_modules/ds-test/src/'
]
solc = '0.8.25'
extra_output = [
  "abi",
  "evm.methodIdentifiers"
]
